# Generated by Django 5.0.6 on 2024-05-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='post.region'),
            preserve_default=False,
        ),
    ]
