# Generated by Django 5.0.6 on 2024-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_region_post_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
