# Generated by Django 5.0.6 on 2024-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_agenda_post_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
